### ISSUE TITLE
Missing run object in some cases

### ISSUE THREAD

**Issue by drobnikj** [apify/keboola-ex-apify#37]
Reported [here](https://apifier.slack.com/archives/C01GVMUSRUN/p1681886366380199)

There is some edge case when the run ends with error.

Error:
```
TypeError: Cannot read property 'status' of null
at Object.waitUntilRunFinished (/usr/src/app/src/helpers/apify_helper.js:28:55)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async runActorTask (/usr/src/app/src/actions/run_task.js:53:34)
at async /usr/src/app/src/index.js:47:21"
```

**Comment by drobnikj** [comment]
Not sure what is causing this, but let's update https://github.com/apify/keboola-ex-apify/issues/26 apify-client and we will see.
